stages:

  # ----------------------------
  # -----AQI + weather merge ---
  # ----------------------------
  merge_weather:
    cmd: python airpollpredictor/dvc_steps/merge_enriched_weather.py --input_weather_prev_years_file airpollpredictor/datasets/weather-clean-data/weather_prev_years.csv --input_weather_cur_year_file airpollpredictor/datasets/weather-clean-data/weather_cur_year.csv --input_aqi_prev_years_file airpollpredictor/datasets/pollutants-enrich-data/aqi_enriched_prev_years.csv --input_aqi_cur_year_file airpollpredictor/datasets/pollutants-enrich-data/aqi_enriched_cur_year.csv --output_file airpollpredictor/datasets/pollutants-weather-merged-data/aqi_all.csv --params params.yaml
    deps:
      - airpollpredictor/datasets/pollutants-enrich-data/aqi_enriched_prev_years.csv
      - airpollpredictor/datasets/pollutants-enrich-data/aqi_enriched_cur_year.csv
      - airpollpredictor/datasets/weather-clean-data/weather_prev_years.csv
      - airpollpredictor/datasets/weather-clean-data/weather_cur_year.csv

      - airpollpredictor/dvc_steps/merge_enriched_weather.py
    outs:
      - airpollpredictor/datasets/pollutants-weather-merged-data/aqi_all.csv


  filter_columns_lgbm_pm_25:
    cmd: python airpollpredictor/dvc_steps/filter_columns_for_model.py --input_file airpollpredictor/datasets/pollutants-weather-merged-data/aqi_all.csv --output_file airpollpredictor/experiments_results/lgbm/6001/aqi_filtered.csv --params params.yaml --params_section lgbm_pm25
    deps:
      - airpollpredictor/datasets/pollutants-weather-merged-data/aqi_all.csv
      - airpollpredictor/dvc_steps/filter_columns_for_model.py
    params:
      - lgbm_pm25
      - columns_filters_gen
    outs:
      - airpollpredictor/experiments_results/lgbm/6001/aqi_filtered.csv


  tune_model_tft_pm_25:
    cmd: python airpollpredictor/dvc_steps/tune_tft_model.py --input_train_file airpollpredictor/experiments_results/lgbm/6001/train.csv --input_val_file airpollpredictor/experiments_results/lgbm/6001/val.csv --output_metrics_file airpollpredictor/experiments_results/tft/6001/metrics.json --output_model_params_file airpollpredictor/experiments_results/tft/6001/model_params.json --output_onnx_file airpollpredictor/experiments_results/tft/6001/model.onnx --mlflow_env_file airpollpredictor/docker_data/env_variables.env --params params.yaml --params_section tft_pm25 #--mlflow_artifact lgbm_pm25_info
    deps:
      - airpollpredictor/experiments_results/lgbm/6001/train.csv
      - airpollpredictor/experiments_results/lgbm/6001/val.csv

      - airpollpredictor/dvc_steps/tune_tft_model.py
    params:
      - lgbm_pm25
      - metric
      - optuna
    outs:
      # - lgbm_pm25_info
      # - airpollpredictor/experiments_results/lgbm/6001/model.onnx
      - airpollpredictor/experiments_results/tft/6001/model_params.json
    metrics:
      - airpollpredictor/experiments_results/tft/6001/metrics.json

