# Set the base image
FROM python:3.10-slim-buster

WORKDIR /airpoll

RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

# Install the required packages
RUN pip install --upgrade pip
RUN pip install psycopg2-binary
RUN pip install boto3
RUN pip install mlflow

ENV MLFLOW_HOST=0.0.0.0
ENV MLFLOW_PORT=5000
ENV MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@db/mlflow
ENV MLFLOW_ARTIFACTS_DESTINATION=s3://air-pol-mlflow-bucket
ENV AWS_ACCESS_KEY_ID=jvcdsd5y4mlm4iv4jn54jpnkyy5a
ENV AWS_SECRET_ACCESS_KEY=j3qc4vai4v4glt46k2i67vf2irppyblov6gcowvfejkx5nc7f3t5i
ENV MLFLOW_S3_ENDPOINT_URL=https://gateway.storjshare.io

CMD mlflow server --host $MLFLOW_HOST --port $MLFLOW_PORT --backend-store-uri $MLFLOW_BACKEND_STORE_URI --artifacts-destination $MLFLOW_ARTIFACTS_DESTINATION --serve-artifacts