#pollutants-codes: &pol_codes [7, 6001, 5, 8]
pollutants-codes:
- 6001

period-settings:
  date_start_train: &date_start_train '2015-01-01'
  date_prev_years_end: &date_prev_years_end '2022-12-31'
  date_current_year_start: &date_current_year_start '2023-01-01'
  current_date: &current_date '2023-06-17'
  last_run_date: &last_run_date '2023-02-12'

split_periods:
#  train_date_to: '2023-04-30'
  #val_date_to: '2023-06-17'
  val_date_to: '2023-05-07'
  forecast_period: &forecast_period 7
  remove_days_at_start: 90

metric: &metric rmse

optuna:
  objective: &objective regression
  n_trials: 50
  n_jobs: 8
  cv_folders: 16
  optimization_direction: minimize

columns_filters_gen: &columns_filters_gen
  use_aqi_cols: true
  use_c_mean_cols: false
  use_c_max_cols: false
  use_c_median_cols: false
  use_c_min_cols: false
  use_pol_cols: false
  use_lag_cols: false
  use_gen_lags_cols: true
  use_weather_cols: true
  pollutants_codes:
  - 6001
  weather_columns:
  - tavg
  - tmin
  - tmax
  - prcp
  - wdir
  - wspd
  - wpgt
  - pres
  date_columns:
  - weekday
  - day
  - month
  - year
  - season
  - is_weekend
  - is_new_year

lgbm_pm25:
  exp_name: lgbm_pm25
  run_name: outliers_no_0507
  pol_id: 6001
  categories:
  - month
  - weekday
  default_category:
  - month
  - weekday
  search_category: false
  default_top_features_count: 30
  default_params:
    n_jobs: -1
    verbosity: -1
    objective: *objective
    metric: *metric
    boosting_type: gbdt
    extra_trees: true
    n_estimators: 2100
    num_leaves: 100
    learning_rate: 0.01
    subsample: 0.7
    subsample_freq: 5
    subsample_for_bin: 100000
    min_child_samples: 30
    reg_alpha: 0.1
    reg_lambda: 0.3
    max_depth: 10
    max_bin: 200
  prediction_value_type: AQI
  columns_filters: *columns_filters_gen
  columns_selected:
  - AQI_PM25
  - month
  - weekday
  - Wx
  - Wy
  - tmin
  - prcp
  - AQI_PM25_lag21d_win7D_agmean_filtNoFilter
  - AQI_PM25_lag7d_win7D_agpercentile(10)_filtNoFilter
  - AQI_PM25_lag7d_win3D_agpercentile(90)_filtNoFilter
  - AQI_PM25_lag10d_win3D_agmedian_filtNoFilter
  - AQI_PM25_lag10d_ewm7_filtNoFilter
  - AQI_PM25_lag28d_win28D_agmean_filtNoFilter
  - AQI_PM25_lag7d_ewm21_filtNoFilter
  - AQI_PM25_lag7d_win14D_agpercentile(90)_filtNoFilter
  - AQI_PM25_lag21d_win14D_agmedian_filtNoFilter
  - AQI_PM25_lag10d_win14D_agpercentile(90)_filtNoFilter
  - AQI_PM25_lag7d_win5D_agmean_filtNoFilter
  - AQI_PM25_lag21d_win28D_agpercentile(10)_filtNoFilter
  - AQI_PM25_lag21d_ewm56_filtweekday